[workspace]
resolver = "3"
members = [
    "flock",
    "compiler/skc",
    "compiler/skc_diag",
    "compiler/skc_ir",
    "compiler/skc_lexer",
    "compiler/skc_macros",
]

[workspace.dependencies]
annotate-snippets = { version = "0.12" }
clap = { version = "4" }
ctrlc = { version = "3" }
skc_diag = { path = "compiler/skc_diag" }
skc_ir = { path = "compiler/skc_ir" }
skc_lexer = { path = "compiler/skc_lexer" }
skc_macros = { path = "compiler/skc_macros" }
darling = { version = "0.23" }
expect-test = { version = "1" }
indexmap = { version = "2" }
insta = { version = "1" }
memchr = { version = "2" }
proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "2" }
thiserror = { version = "2" }
unicode-ident = { version = "1" }
yansi = { version = "1" }
