[package]
name = "skc"
version = "0.0.0"
edition = "2024"

[dependencies]
annotate-snippets.workspace = true
clap = { workspace = true, features = ["derive"] }
ctrlc.workspace = true
skc_diag.workspace = true
skc_ir.workspace = true
skc_lexer.workspace = true
skc_macros.workspace = true
indexmap.workspace = true
thiserror.workspace = true
unicode-ident.workspace = true
yansi.workspace = true

[dev-dependencies]
expect-test.workspace = true
